### ISSUE TITLE
基于用户的完成工单配额

### ISSUE THREAD

**Issue by ljm12914** [fyscu/foc_be#9]

**Comment by ljm12914** [comment]
用户在一天内有一定的给志愿时长配额，以工单个数记，推荐是一周五个工单，实现方式推荐是每周一凌晨0:00重置所有用户字段到5

用户每创建一个工单，则暂时扣1配额；该工单如果异常结束（用户强制结束、技术员强制结束），则配额回到用户账户；如果工单正常维修完毕，则配额不返还。

后端在结束工单时需要进行判断，并可能会给用户增加配额。

**Comment by ljm12914** [comment]
配额写到库里，可以用既有字段

**Comment by wjlfish** [comment]
已经通过新分配逻辑和既有字段available实现，可在config中调整周限额，每周一00:00重置限额。异常结束也已设置返还逻辑。
